# Generated by Django 3.1.4 on 2020-12-25 05:13

from django.db import migrations, models
import django.db.models.deletion
import myuser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amount_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='buyer_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=100)),
                ('buyer_phone_number', models.CharField(blank=True, max_length=20)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_sex', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='myuser_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ImageField(blank=True, null=True, upload_to=myuser.models.user_directory_path)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.IntegerField()),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('location', models.CharField(default='BeiJing', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('wares', models.ManyToManyField(through='myuser.amount_model', to='myuser.ware')),
            ],
        ),
        migrations.CreateModel(
            name='order_table_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=100)),
                ('buyer_phone_number', models.CharField(blank=True, max_length=20)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_sex', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('process_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myuser.myuser_model')),
            ],
        ),
        migrations.CreateModel(
            name='order_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('order_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.order_table_model')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.ware')),
            ],
        ),
        migrations.AddField(
            model_name='amount_model',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.ware'),
        ),
        migrations.AddField(
            model_name='amount_model',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.warehouse'),
        ),
    ]
