# Generated by Django 3.1.4 on 2020-12-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_table_model',
            name='process_user',
        ),
    ]
